# Generated by Django 5.0.6 on 2024-06-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='number',
            new_name='phone_number',
        ),
    ]
